---
- name: Ensure dirmngr is installed (gnupg dependency).
  ansible.builtin.apt:
    name: dirmngr
    state: present

- name: Ensure pip is installed.
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Add ansible repository.
  ansible.builtin.apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: true

- name: Install Ansible.
  ansible.builtin.apt:
    name: ansible
    state: "{{ ansible_package_state }}"
