---
- name: Ensure pip is installed.
  ansible.builtin.package:
    name: python3-pip
    state: "{{ ansible_package_state }}"

- name: Install Ansible.
  ansible.builtin.package:
    name: ansible
    state: "{{ ansible_package_state }}"
