---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install pip on Debian or Ubuntu
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes
  when: "'ansible_os_family' in ansible_facts.packages"

- name: Install pip on RedHat, Rocky or Fedora
  ansible.builtin.yum:
    name: python-pip
    state: present
  become: yes
  when: "'redhat' in ansible_facts.packages"

- name: Install Ansible via Pip.
  ansible.builtin.pip:
    name: ansible
    executable: "{{ ansible_pip_executable | default(omit) }}"
    version: "{{ ansible_install_version_pip | default(omit) }}"
    extra_args: "{{ ansible_install_pip_extra_args | default(omit) }}"
