---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure pip is installed via the package manager
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Ansible via Pip.
  ansible.builtin.pip:
    name: ansible
    executable: "{{ ansible_pip_executable | default(omit) }}"
    version: "{{ ansible_install_version_pip | default(omit) }}"
    extra_args: "{{ ansible_install_pip_extra_args | default(omit) }}"
